eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver