spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    config:
      customer-url: http://localhost:8222/api/v1/customers
      payment-url: http://localhost:8222/api/v1/payments
      product-url: http://localhost:8222/api/v1/products

server:
  port: 8070
